version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: covaldys_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: CovaldysPilot.API/Dockerfile
    container_name: covaldys_api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  angular:
    build:
      context: ../CovaldysPilot_FRONT
      dockerfile: Dockerfile
    container_name: covaldys_angular
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  sqlserver_data: